
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sheila
 */
public class AgregarAparatos extends javax.swing.JFrame {

    /**
     * Creates new form AgregarAparatos
     */
    int idactual;
    boolean modifica=false;
    boolean actualiza=false;
    ListadoAparatos L;
    ArrayList<Aparatos> Misaparatos;
    public AgregarAparatos(ArrayList<Aparatos> LAparatos) {
        initComponents();
        Misaparatos=LAparatos;
    }
    
     public AgregarAparatos (ArrayList<Aparatos> LAparatos , ListadoAparatos la ) 
    {
        initComponents();
        Misaparatos=LAparatos;
        L=la;
        actualiza=true;
        
    }

     public AgregarAparatos (ArrayList<Aparatos> LAparatos , ListadoAparatos la , String minombre, String mifuncion, int miedadmin, int miedadmax, int miid, String mibaja)
     {
       initComponents();
        Misaparatos=LAparatos;
        L=la;
        actualiza=true;
        modifica=true;
        idactual=miid;
        
        txtnom.setText(minombre);
        txtfunc.setText(mifuncion);
        txtedadmin.setText(String.valueOf(miedadmin));
        txtedadmax.setText(String.valueOf(miedadmax));
        if (mibaja.equals("SI"))
            baja.setSelected(true);
        else
        {
            baja.setSelected(false);               
        }
      
     }
     
    private AgregarAparatos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        baja = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtfunc = new javax.swing.JTextField();
        txtedadmin = new javax.swing.JTextField();
        txtedadmax = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Funcion");

        jLabel3.setText("Edad minima");

        jLabel4.setText("Edad maxima");

        baja.setText("SI");

        jLabel5.setText("Dado de baja");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(baja)
                    .addComponent(txtnom, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(txtfunc)
                    .addComponent(txtedadmin)
                    .addComponent(txtedadmax))
                .addGap(90, 90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtfunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtedadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtedadmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baja)
                    .addComponent(jLabel5))
                .addGap(11, 11, 11)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private void Limpiar()
     {
         txtnom.setText("");
         txtfunc.setText("");
         txtedadmin.setText("");
         txtedadmax.setText("");
         baja.setSelected(false);
         
                 
     }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          if (modifica)
        {
          //recuperar aparato actual del arraylist
            Aparatos apaactual= Misaparatos.get(idactual);
            //pasar datos del formulario a apaactual
            int idaparato=Misaparatos.size();
        apaactual.Setnombre(txtnom.getText());
        apaactual.Setfuncion(txtfunc.getText());
        apaactual.Setedadmin(Integer.parseInt(txtedadmin.getText()));
        apaactual.Setedadmax(Integer.parseInt(txtedadmax.getText()));
        apaactual.Setbaja(baja.isSelected());
       
        JOptionPane.showMessageDialog(null,"Se ha modificado el aparato", "Atención" , JOptionPane.INFORMATION_MESSAGE);
        }
        
        else
        {
        if (txtnom.getText().equals("")||txtedadmax.getText().equals("")||txtedadmin.getText().equals("")||txtfunc.getText().equals(""))
        
           JOptionPane.showMessageDialog(null,"ERROR, datos incompletos", "Atención" , JOptionPane.INFORMATION_MESSAGE);
        
        else{  
       
        Aparatos nuevoaparato=new Aparatos();
        int idaparato=Misaparatos.size();
        nuevoaparato.Setnombre(txtnom.getText());
        nuevoaparato.Setfuncion(txtfunc.getText());
        nuevoaparato.Setedadmin(Integer.parseInt(txtedadmin.getText()));
        nuevoaparato.Setedadmax(Integer.parseInt(txtedadmax.getText()));
        nuevoaparato.Setbaja(baja.isSelected());
        nuevoaparato.Setid(idaparato);
       
        Misaparatos.add(nuevoaparato);
        System.out.println(Misaparatos.size());
        Limpiar();
        JOptionPane.showMessageDialog(null,"Nuevo aparato Añadido", "Atención" , JOptionPane.INFORMATION_MESSAGE);
          
        }
        }           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
         if (actualiza)
        
        L.CrearListaAparatos();
        
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox baja;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtedadmax;
    private javax.swing.JTextField txtedadmin;
    private javax.swing.JTextField txtfunc;
    private javax.swing.JTextField txtnom;
    // End of variables declaration//GEN-END:variables
}
