
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sheila
 */
public class ListadoAparatos extends javax.swing.JFrame {
    int Nfila;
    

    /**
     * Creates new form ListadoAparatos
     */
    ArrayList<Aparatos> Misaparatos;
    DefaultTableModel mimodelo;
    public ListadoAparatos(ArrayList<Aparatos> LAparatos) {
        initComponents();
        Misaparatos=LAparatos;
        CrearListaAparatos();
    }
    
    private void configurartabla(){
        mimodelo=new DefaultTableModel();
        mimodelo.addColumn("nombre");
        mimodelo.addColumn("funcion");
        mimodelo.addColumn("edad minima");
        mimodelo.addColumn("edad maxima");
        mimodelo.addColumn("baja");
        Tabla.setModel(mimodelo);
    }
    
    public void CrearListaAparatos()
    {
        configurartabla();
        for (int i=0; i<Misaparatos.size(); i++){
            //recupera un aparato en posicion i
            Aparatos aparatoactual= Misaparatos.get(i);
            //crear fila con datos del aparato
            Object[] fila= new Object[6];
            //pasa datos a la fila
            fila[0]=aparatoactual.getnombre();
            fila[1]=aparatoactual.getfuncion();
            fila[2]=String.valueOf(aparatoactual.getedadmin());
            fila[3]=String.valueOf(aparatoactual.getedadmax());
            if (aparatoactual.getbaja())
             fila [4]="SI";
            else
             fila[4]="NO";  
            fila[5]=String.valueOf(aparatoactual.getid());
            mimodelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(45, 45, 45)
                        .addComponent(jButton3)
                        .addGap(29, 29, 29)
                        .addComponent(jButton1)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        Nfila= Tabla.getSelectedRow();
    }//GEN-LAST:event_TablaMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AgregarAparatos na=new AgregarAparatos (Misaparatos , this);
        na.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //recupero el dato de la fila para poder modificarlo
        
        String nom = Tabla.getModel().getValueAt(Nfila, 0).toString();
        String fun= Tabla.getModel().getValueAt(Nfila, 1).toString();
        int edadmin= Integer.parseInt(Tabla.getModel().getValueAt(Nfila, 2).toString());
        int edadmax= Integer.parseInt(Tabla.getModel().getValueAt(Nfila, 3).toString());
        int miid = Integer.parseInt(Tabla.getModel().getValueAt(Nfila, 4).toString());
        String baja= Tabla.getModel().getValueAt(Nfila, 5).toString();
        
        
        
        AgregarAparatos NA =new AgregarAparatos (Misaparatos, this , nom, fun , edadmin , edadmax , miid, baja);
        NA.setVisible(true);
                                        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}