
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sheila
 */
public class ListadoPersonas extends javax.swing.JFrame {
    int nfila;

    /**
     * Creates new form ListadoPersonas
     */
    ArrayList<Persona> MisPersonas;
    DefaultTableModel mimodelo;
    public ListadoPersonas(ArrayList<Persona>LPersona) {
        initComponents();
        MisPersonas=LPersona;
        CrearListaPersona();
    }
    
    private void configurartabla(){
        mimodelo=new DefaultTableModel();
        mimodelo.addColumn("nombre");
        mimodelo.addColumn("apellido");
        mimodelo.addColumn("edad");
        mimodelo.addColumn("fechan");
        mimodelo.addColumn("direccion");
        mimodelo.addColumn("tel");
        mimodelo.addColumn("idpersona");
        mimodelo.addColumn("ficha");
        mimodelo.addColumn("activo");
        Tabla.setModel(mimodelo);
    }
    
    public void CrearListaPersona()
    {
        configurartabla();
        for (int i=0; i<MisPersonas.size(); i++){
            //recupera una persona en posicion i
            Persona personaactual= MisPersonas.get(i);
            //crear fila con datos de la persona
            Object[] fila= new Object[9];
            //pasa datos a la fila
            fila[0]=personaactual.getnombre();
            fila[1]=personaactual.getapellido();
            fila[2]=personaactual.getedad();
            fila[3]=personaactual.getfecha();
            fila[4]=personaactual.getdireccion();
            fila[5]=personaactual.gettelefono();
            fila[6]=String.valueOf(personaactual.getid());
            
            if (personaactual.getficha())
             fila[7]="Entrego";
            else
                fila[7]="No Entrego";
            
            if (personaactual.getactivo())
                fila[8]="Activo";
            else
               fila[8]="Inactivo"; 
                        
           
            mimodelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        nfila=Tabla.getSelectedRow();
        
    }//GEN-LAST:event_TablaMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Personas np=new Personas (MisPersonas , this);
        np.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //recupero el dato de la fila para poder modificarlo
        String nom = Tabla.getModel().getValueAt(nfila, 0).toString();
        String ap= Tabla.getModel().getValueAt(nfila, 1).toString();
        int edad= Integer.parseInt(Tabla.getModel().getValueAt(nfila, 2).toString());
        String fecha=Tabla.getModel().getValueAt(nfila, 3).toString();
        String dir= Tabla.getModel().getValueAt(nfila, 4).toString();
        String tel= Tabla.getModel().getValueAt(nfila, 5).toString();
        int idpers = Integer.parseInt(Tabla.getModel().getValueAt(nfila, 6).toString());
        String ficha= Tabla.getModel().getValueAt(nfila, 7).toString();
        String activo= Tabla.getModel().getValueAt(nfila, 8).toString();
        
        
        Personas NP =new Personas (MisPersonas, this , nom, ap , edad, fecha, dir , tel , idpers , ficha, activo);
        NP.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

      //To change body of generated methods, choose Tools | Templates.
    
}
