
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sheila
 */
public class NuevoHorario extends javax.swing.JFrame {

    /**
     * Creates new form NuevoHorario
     */
    int idactual;
    boolean modifica=false;
    ListadoHorarios L;
    boolean actualiza=false;
    ArrayList<Horarios> MisHorarios;
    public NuevoHorario(ArrayList<Horarios> LHorarios) {
        initComponents();
        MisHorarios=LHorarios;
        
    }
    
    public NuevoHorario(ArrayList<Horarios> LHorarios , ListadoHorarios lh ) 
    {
        initComponents();
        MisHorarios=LHorarios;
        L=lh;
        actualiza=true;
        
    }
    
    public NuevoHorario (ArrayList<Horarios> LHorarios , ListadoHorarios lh , String midia, int mihoraini, int mihorafin , int micantpers , int miid) 
    {
        initComponents();
        MisHorarios=LHorarios;
        L=lh;
        actualiza=true;
        modifica=true;
        idactual=miid;
        
        if (midia.equals("LUNES"))
            Lunes.setSelected(true);
        if (midia.equals("MARTES"))
            Martes.setSelected(true);
        if (midia.equals("MIERCOLES"))
            Miercoles.setSelected(true);
        if (midia.equals("JUEVES"))
            Jueves.setSelected(true);
        if (midia.equals("VIERNES"))
            Viernes.setSelected(true);
        Horaini.setText(String.valueOf(mihoraini));
        Horafin.setText(String.valueOf(mihorafin));
        cantpers.setText(String.valueOf(micantpers));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Horaini = new javax.swing.JTextField();
        Horafin = new javax.swing.JTextField();
        cantpers = new javax.swing.JTextField();
        Lunes = new javax.swing.JRadioButton();
        Martes = new javax.swing.JRadioButton();
        Miercoles = new javax.swing.JRadioButton();
        Jueves = new javax.swing.JRadioButton();
        Viernes = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Días");

        jLabel2.setText("Hora de Inicio");

        jLabel3.setText("Hora de Finalización");

        jLabel4.setText("Cantidad Personas");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Horaini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorainiActionPerformed(evt);
            }
        });

        buttonGroup1.add(Lunes);
        Lunes.setText("Lunes");

        buttonGroup1.add(Martes);
        Martes.setText("Martes");

        buttonGroup1.add(Miercoles);
        Miercoles.setText("Miercoles");

        buttonGroup1.add(Jueves);
        Jueves.setText("Jueves");

        buttonGroup1.add(Viernes);
        Viernes.setText("Viernes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cantpers, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Horafin, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Horaini, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Martes)
                    .addComponent(Lunes)
                    .addComponent(Viernes)
                    .addComponent(Miercoles)
                    .addComponent(Jueves))
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Lunes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Martes)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Miercoles)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jueves)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(Viernes)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Horaini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Horafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantpers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

     private void Limpiar()
     {
         Horaini.setText("");
         Horafin.setText("");
         cantpers.setText("");
         Lunes.setSelected(false);
         Martes.setSelected(false);
         Miercoles.setSelected(false);
         Jueves.setSelected(false);
         Viernes.setSelected(false);
                 
     }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         if (modifica)
        {
          //recuperar horario actual del arraylist
            Horarios horactual= MisHorarios.get(idactual);
            //pasar datos del formulario a horactual
       
        if (Lunes.isSelected())    
         horactual.Setdia("Lunes");
        if (Martes.isSelected())
         horactual.Setdia("Martes");
        if (Miercoles.isSelected()) 
         horactual.Setdia("Miercoles");
        if (Jueves.isSelected()) 
         horactual.Setdia("Jueves");
        if (Viernes.isSelected()) 
         horactual.Setdia("Viernes");        
        horactual.Sethoraini(Integer.parseInt(Horaini.getText()));
        horactual.Sethorafin(Integer.parseInt(Horafin.getText()));
        horactual.Setcantpersona(Integer.parseInt(cantpers.getText()));
        
        
        
      
        JOptionPane.showMessageDialog(null,"Se ha modificado el horario", "Atención" , JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        if (Horaini.getText().equals("")|| Horafin.getText().equals("")||cantpers.getText().equals("") )
        
            JOptionPane.showMessageDialog(null,"ERROR, datos incompletos", "Atención" , JOptionPane.INFORMATION_MESSAGE);
        
        else{
        
        if (Lunes.isSelected()){
         Horarios NuevoHorario=new Horarios();
        
         int idhorario=MisHorarios.size();
          NuevoHorario.Setdia("LUNES");
        NuevoHorario.Setidhorario(idhorario);
        NuevoHorario.Sethoraini(Integer.parseInt(Horaini.getText()));
        NuevoHorario.Sethorafin(Integer.parseInt(Horafin.getText()));
        NuevoHorario.Setcantpersona(Integer.parseInt(cantpers.getText()));   
        
         MisHorarios.add(NuevoHorario);
        System.out.println(MisHorarios.size());
        Limpiar();
        JOptionPane.showMessageDialog(null,"Nuevo Horario Añadido", "Atención" , JOptionPane.INFORMATION_MESSAGE);
        }
        
        if (Martes.isSelected()){
         Horarios NuevoHorario2=new Horarios();
        
         int idhorario=MisHorarios.size();
          NuevoHorario2.Setdia("MARTES");
        NuevoHorario2.Setidhorario(idhorario);
        NuevoHorario2.Sethoraini(Integer.parseInt(Horaini.getText()));
        NuevoHorario2.Sethorafin(Integer.parseInt(Horafin.getText()));
        NuevoHorario2.Setcantpersona(Integer.parseInt(cantpers.getText()));   
        
         MisHorarios.add(NuevoHorario2);
        System.out.println(MisHorarios.size());
        Limpiar();
        JOptionPane.showMessageDialog(null,"Nuevo Horario Añadido", "Atención" , JOptionPane.INFORMATION_MESSAGE);
        }
        
        if (Miercoles.isSelected()){
         Horarios NuevoHorario3=new Horarios();
        
         int idhorario=MisHorarios.size();
          NuevoHorario3.Setdia("MIERCOLES");
        NuevoHorario3.Setidhorario(idhorario);
        NuevoHorario3.Sethoraini(Integer.parseInt(Horaini.getText()));
        NuevoHorario3.Sethorafin(Integer.parseInt(Horafin.getText()));
        NuevoHorario3.Setcantpersona(Integer.parseInt(cantpers.getText()));   
        
         MisHorarios.add(NuevoHorario3);
        System.out.println(MisHorarios.size());
        Limpiar();
        JOptionPane.showMessageDialog(null,"Nuevo Horario Añadido", "Atención" , JOptionPane.INFORMATION_MESSAGE);
        }
        
        if (Jueves.isSelected()){
         Horarios NuevoHorario4=new Horarios();
        
         int idhorario=MisHorarios.size();
          NuevoHorario4.Setdia("JUEVES");
        NuevoHorario4.Setidhorario(idhorario);
        NuevoHorario4.Sethoraini(Integer.parseInt(Horaini.getText()));
        NuevoHorario4.Sethorafin(Integer.parseInt(Horafin.getText()));
        NuevoHorario4.Setcantpersona(Integer.parseInt(cantpers.getText()));   
         
        
        MisHorarios.add(NuevoHorario4);
        System.out.println(MisHorarios.size());
        Limpiar();
        JOptionPane.showMessageDialog(null,"Nuevo Horario Añadido", "Atención" , JOptionPane.INFORMATION_MESSAGE);
        }
        
        if (Viernes.isSelected()){
         Horarios NuevoHorario5=new Horarios();
        
         int idhorario=MisHorarios.size();
          NuevoHorario5.Setdia("VIERNES");
        NuevoHorario5.Setidhorario(idhorario);
        NuevoHorario5.Sethoraini(Integer.parseInt(Horaini.getText()));
        NuevoHorario5.Sethorafin(Integer.parseInt(Horafin.getText()));
        NuevoHorario5.Setcantpersona(Integer.parseInt(cantpers.getText()));   
        
        
         MisHorarios.add(NuevoHorario5);
        System.out.println(MisHorarios.size());
        Limpiar();
        JOptionPane.showMessageDialog(null,"Nuevo Horario Añadido", "Atención" , JOptionPane.INFORMATION_MESSAGE);
      }
     }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        if (actualiza)
        
        L.CrearListaHorarios();
    }//GEN-LAST:event_formWindowClosed

    private void HorainiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorainiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HorainiActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Horafin;
    private javax.swing.JTextField Horaini;
    private javax.swing.JRadioButton Jueves;
    private javax.swing.JRadioButton Lunes;
    private javax.swing.JRadioButton Martes;
    private javax.swing.JRadioButton Miercoles;
    private javax.swing.JRadioButton Viernes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cantpers;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
